import { BackendOSError } from "./errors.js";
import { coerceRow, coerceRows } from "./coerce.js";
import type { BackendOSClient, BackendOSConfig } from "./types.js";

interface ApiEnvelope {
  data?: unknown;
  error?: { code?: string; message?: string; details?: unknown };
}

function makeTableClient(baseUrl: string, accessKey: string, fetchImpl: typeof fetch, table: string, dateColumns: readonly string[]) {
  async function request(operation: string, body: unknown): Promise<unknown> {
    const res = await fetchImpl(`${baseUrl}/v1/${table}/${operation}`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: `Bearer ${accessKey}`,
      },
      body: JSON.stringify(body ?? {}),
    });

    let json: ApiEnvelope | null = null;
    try {
      json = (await res.json()) as ApiEnvelope;
    } catch {
      // empty/non-JSON body
    }

    if (!res.ok) {
      throw new BackendOSError(json?.error?.message ?? res.statusText, json?.error?.code, res.status, json?.error?.details);
    }
    return json?.data;
  }

  return {
    findMany: async (args?: unknown) => coerceRows(await request("findMany", args ?? {}), dateColumns),
    findUnique: async (args: unknown) => {
      const row = await request("findUnique", args);
      return row ? coerceRow(row, dateColumns) : null;
    },
    create: async (args: unknown) => {
      const result = await request("create", args);
      return Array.isArray(result) ? coerceRows(result, dateColumns) : coerceRow(result, dateColumns);
    },
    update: async (args: unknown) => coerceRows(await request("update", args), dateColumns),
    delete: async (args: unknown) => coerceRows(await request("delete", args), dateColumns),
    count: async (args?: unknown) => Number(await request("count", args ?? {})),
  };
}

/**
 * Creates a type-safe BackendOS client. Pass the `Database` type generated by
 * `backendos generate` as the generic parameter to get full autocomplete and compile-time
 * validation for every table (`backendos.users.findMany()`, etc).
 *
 * Most projects won't call this directly - the generated file exports a `createBackendOS`
 * already bound to your schema, so you just do:
 *
 *   import { createBackendOS } from "./backendos-types";
 *   const backendos = createBackendOS({ url, accessKey });
 */
export function createBackendOS<DB>(config: BackendOSConfig): BackendOSClient<DB> {
  const fetchImpl = config.fetch ?? globalThis.fetch;
  if (!fetchImpl) {
    throw new Error("No fetch implementation available in this runtime; pass one via `fetch` in the config.");
  }
  const baseUrl = config.url.replace(/\/+$/, "");

  const cache = new Map<string, ReturnType<typeof makeTableClient>>();
  return new Proxy({} as BackendOSClient<DB>, {
    get(_target, prop) {
      if (typeof prop !== "string") return undefined;
      let client = cache.get(prop);
      if (!client) {
        const dateColumns = config.schema?.[prop]?.dateColumns ?? [];
        client = makeTableClient(baseUrl, config.accessKey, fetchImpl, prop, dateColumns);
        cache.set(prop, client);
      }
      return client;
    },
  });
}
