// AUTO-GENERATED by `backendos generate`. Do not edit by hand.
// Source schema: "proj_c91c17fca5c0a280a6d0" · generated 2026-09-02T09:43:05.858Z
/* eslint-disable */


export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface PostsRow {
  id: string;
  userId: string;
  title: string;
  content: string | null;
  createdAt: Date;
}

export interface PostsInsert {
  id?: string;
  userId: string;
  title: string;
  content?: string | null;
  createdAt?: Date;
}

export interface PostsUpdate {
  id?: string;
  userId?: string;
  title?: string;
  content?: string | null;
  createdAt?: Date;
}

export interface UsersRow {
  id: string;
  name: string;
  email: string | null;
  age: number | null;
  createdAt: Date;
}

export interface UsersInsert {
  id?: string;
  name: string;
  email?: string | null;
  age?: number | null;
  createdAt?: Date;
}

export interface UsersUpdate {
  id?: string;
  name?: string;
  email?: string | null;
  age?: number | null;
  createdAt?: Date;
}

export interface Database {
  posts: { Row: PostsRow; Insert: PostsInsert; Update: PostsUpdate };
  users: { Row: UsersRow; Insert: UsersInsert; Update: UsersUpdate };
}

export const backendOSSchema = {
  posts: { dateColumns: ["createdAt"] as const },
  users: { dateColumns: ["createdAt"] as const },
} as const;

import { createBackendOS as _createBackendOS } from "@backendos/client";
import type { BackendOSClient } from "@backendos/client";

export interface CreateBackendOSConfig {
  url: string;
  accessKey: string;
}

export function createBackendOS(config: CreateBackendOSConfig): BackendOSClient<Database> {
  return _createBackendOS<Database>({ ...config, schema: backendOSSchema });
}
