// AUTO-GENERATED by `backendos generate`. Do not edit by hand.
// Source schema: "proj_7f6fc6d8922ded152a75" · generated 2026-09-02T09:54:03.607Z
/* eslint-disable */


export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface ConversationsRow {
  id: string;
  name: string | null;
  userCount: number | null;
}

export interface ConversationsInsert {
  id?: string;
  name?: string | null;
  userCount?: number | null;
}

export interface ConversationsUpdate {
  id?: string;
  name?: string | null;
  userCount?: number | null;
}

export interface Database {
  conversations: { Row: ConversationsRow; Insert: ConversationsInsert; Update: ConversationsUpdate };
}

export const backendOSSchema = {
  conversations: { dateColumns: [] as const },
} as const;

import { createBackendOS as _createBackendOS } from "@backendos/client";
import type { BackendOSClient } from "@backendos/client";

export interface CreateBackendOSConfig {
  url: string;
  accessKey: string;
}

export function createBackendOS(config: CreateBackendOSConfig): BackendOSClient<Database> {
  return _createBackendOS<Database>({ ...config, schema: backendOSSchema });
}
