import { pgUdtToTsType } from "./pg-type-map.js";
import { toPascalCase } from "./naming.js";
import type { ColumnSchema, DatabaseSchema, TableSchema } from "./types.js";

const IDENT_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function printKey(name: string): string {
  return IDENT_RE.test(name) ? name : JSON.stringify(name);
}

function fieldType(col: ColumnSchema): string {
  const { ts } = pgUdtToTsType(col.udtName);
  return col.isNullable ? `${ts} | null` : ts;
}

function isOptionalForInsert(col: ColumnSchema): boolean {
  return col.isNullable || col.columnDefault !== null || col.isIdentity;
}

function printInterface(name: string, table: TableSchema, mode: "row" | "insert" | "update"): string {
  const lines = table.columns.map((col) => {
    const optional = mode === "update" || (mode === "insert" && isOptionalForInsert(col));
    return `  ${printKey(col.apiName)}${optional ? "?" : ""}: ${fieldType(col)};`;
  });
  return `export interface ${name} {\n${lines.join("\n")}\n}`;
}

/**
 * Generates a single self-contained TypeScript module: Row/Insert/Update types for every
 * table, a `Database` map used for full client autocomplete, a runtime schema descriptor
 * (needed so the client can turn ISO date strings back into real `Date` objects), and a
 * pre-bound `createBackendOS()` factory so consumers don't have to pass generics by hand.
 */
export function generateClientModule(db: DatabaseSchema): string {
  const header = `// AUTO-GENERATED by \`backendos generate\`. Do not edit by hand.
// Source schema: "${db.schemaName}" · generated ${db.generatedAt}
/* eslint-disable */
`;

  const jsonType = `export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];`;

  const tableBlocks = db.tables.map((table) => {
    const pascal = toPascalCase(table.name);
    return [
      printInterface(`${pascal}Row`, table, "row"),
      printInterface(`${pascal}Insert`, table, "insert"),
      printInterface(`${pascal}Update`, table, "update"),
    ].join("\n\n");
  });

  const databaseEntries = db.tables.map((table) => {
    const pascal = toPascalCase(table.name);
    return `  ${printKey(table.name)}: { Row: ${pascal}Row; Insert: ${pascal}Insert; Update: ${pascal}Update };`;
  });
  const databaseType = `export interface Database {\n${databaseEntries.join("\n")}\n}`;

  const schemaEntries = db.tables.map((table) => {
    const dateColumns = table.columns.filter((c) => pgUdtToTsType(c.udtName).isDate).map((c) => JSON.stringify(c.apiName));
    return `  ${printKey(table.name)}: { dateColumns: [${dateColumns.join(", ")}] as const },`;
  });
  const schemaConst = `export const backendOSSchema = {\n${schemaEntries.join("\n")}\n} as const;`;

  const clientWrapper = `import { createBackendOS as _createBackendOS } from "@backendos/client";
import type { BackendOSClient } from "@backendos/client";

export interface CreateBackendOSConfig {
  url: string;
  accessKey: string;
}

export function createBackendOS(config: CreateBackendOSConfig): BackendOSClient<Database> {
  return _createBackendOS<Database>({ ...config, schema: backendOSSchema });
}`;

  return [header, jsonType, tableBlocks.join("\n\n"), databaseType, schemaConst, clientWrapper].join("\n\n") + "\n";
}
